# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vbrabandt <vbrabandt@proton.me>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/06/07 13:13:47 by vbraband          #+#    #+#              #
#    Updated: 2024/07/10 03:37:27 by vbrabandt        ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
SRCS = srcs/*.c

ALL:
	gcc $(SRCS) -o $(NAME)
clean:
	rm -f *.O 

fclean: clean
	rm -f $(NAME)

re: fclean re
